### ISSUE TITLE
Hierarchical CLI

### ISSUE THREAD

**Issue by howardwu** [ArgusHQ/wagyu#39]
### Summary

Rearchitect the CLI to provide coin specific flags, which can be accessible via the `--help` command.

**Comment by raychu86** [comment]
Requires CLI overhaul with subcommands. 

Additional support for features required:
- [ ] Additional address types
- [ ] Extended keys
- [ ] Mnemonics 
- [ ] Key/Mnemonic imports

**Comment by raychu86** [comment]
#61
